config/routes.rb
Rails.application.routes.draw do
  resources :parkings
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/parking.rb
# == Schema Information
#
# Table name: parkings
#
#  id           :integer          not null, primary key
#  name         :string
#  address      :string
#  available    :boolean
#  has_camera   :boolean
#  has_watchman :boolean
#  zip_code     :string
#  city         :string
#  main_picture :string
#  price_month  :money
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  lat          :float
#  district     :string
#  slug         :string
#

class Parking < ApplicationRecord
  extend FriendlyId
  friendly_id :slug_candidates, use: [:slugged, :history, :finders]

  after_save :geocode_address
  before_validation :check_changes
  before_validation :set_district, :on => :create
  validates :name, :slug, :city, presence: true

  def slug_candidates
    [
      :name,
      [:name, :city]
    ]
  end

  private

  def set_district
    return unless city_changed? || zip_code_changed?
    self.district = self.city.upcase == "PARIS" ? self.zip_code.split(//).last(2).join : "O"
  end

  def check_changes
    self.check_address = address_changed? || zip_code_changed? || city_changed? || false
  end

  def geocode_address
    return unless self.check_address
    begin
      geo = Geokit::Geocoders::MultiGeocoder.geocode("#{address} #{zip_code} #{city}")
    rescue => e
      Rails.logger.error e.message
    end
    unless geo.success
      message = "Could not Geocode this : #{address} #{zip_code} #{city}"
      errors.add(:base, message)
      Rails.logger.error message
    else
      self.lat, self.lng = geo.lat,geo.lng
      self.city = geo.city
      self.check_address = true
    end
    self.save!
  end
  handle_asynchronously :geocode_address
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_filter :set_map_markers
  before_filter :set_page_controller

  include ApplicationHelper

  private

  def set_map_markers
    return unless is_page_controller?
    @map_parkings = Parking.all
    @hash = Gmaps4rails.build_markers(@map_parkings) do |parking, marker|
      marker.lat parking.lat
      marker.lng parking.lng
      marker.title parking.name
      marker.infowindow "<ul><li>Name: #{parking.name}</li> <li>Address: #{parking.address}</li> <li>Zip_code: #{parking.zip_code}</li> <li>City: #{parking.city}</li> <li>Price: #{parking.price_month}</li><li><a href='#{parking_path(parking)}'><img src='#{parking.main_picture}' alt='Picture' height='auto' width='100px' /></a></li></ul>"
    end
  end

  def set_page_controller
    is_page_controller?
  end

end

app/controllers/parkings_controller.rb
class ParkingsController < ApplicationController
  before_action :set_parking, only: [:show, :edit, :update, :destroy]

  # GET /parkings
  def index
    @parkings = Parking.all
  end

  # GET /parkings/1
  def show
    if request.path != parking_path(@parking)
      redirect_to @parking, status: :moved_permanently
    end
  end

  # GET /parkings/new
  def new
    @parking = Parking.new
  end

  # GET /parkings/1/edit
  def edit
  end

  # POST /parkings
  def create
    @parking = Parking.new(parking_params)

    if @parking.save
      redirect_to @parking, notice: 'Parking was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /parkings/1
  def update
    if @parking.update(parking_params)
      redirect_to @parking, notice: 'Parking was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /parkings/1
  def destroy
    @parking.destroy
    redirect_to parkings_url, notice: 'Parking was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_parking
      @parking = Parking.friendly.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def parking_params
      params.require(:parking).permit(:name, :address, :available, :has_camera, :has_watchman, :zip_code, :city, :main_picture, :price_month)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def is_page_controller?
    @is_page_controller ||= controller_name == 'pages'
  end
end

app/helpers/flashes_helper.rb
module FlashesHelper
  def user_facing_flashes
    flash.to_hash.slice("alert", "error", "notice", "success")
  end
end

app/views/application/_analytics.html.erb
<% if ENV["SEGMENT_KEY"] %>
  <script type="text/javascript">
    window.analytics=window.analytics||[],window.analytics.methods=["identify","group","track","page","pageview","alias","ready","on","once","off","trackLink","trackForm","trackClick","trackSubmit"],window.analytics.factory=function(t){return function(){var a=Array.prototype.slice.call(arguments);return a.unshift(t),window.analytics.push(a),window.analytics}};for(var i=0;i<window.analytics.methods.length;i++){var key=window.analytics.methods[i];window.analytics[key]=window.analytics.factory(key)}window.analytics.load=function(t){if(!document.getElementById("analytics-js")){var a=document.createElement("script");a.type="text/javascript",a.id="analytics-js",a.async=!0,a.src=("https:"===document.location.protocol?"https://":"http://")+"cdn.segment.com/analytics.js/v1/"+t+"/analytics.min.js";var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(a,n)}},window.analytics.SNIPPET_VERSION="2.0.9",
    window.analytics.load("<%= ENV["SEGMENT_KEY"] %>");
    window.analytics.page();
  </script>
<% end %>

app/views/application/_css_overrides.html.erb
<% if Rails.env.test? %>
  <style type="text/css">
    * {
      transition-property: none !important;
    }
  </style>
<% end %>

app/views/application/_flashes.html.erb
<% if flash.any? %>
  <div class="flashes">
    <% user_facing_flashes.each do |key, value| -%>
      <div class="flash-<%= key %>"><%= value %></div>
    <% end -%>
  </div>
<% end %>

app/views/application/_javascript.html.erb
<%= javascript_include_tag :application %>

<%= yield :javascript %>

<%= render "analytics" %>

<% if Rails.env.test? %>
  <%= javascript_tag do %>
    $.fx.off = true;
    $.ajaxSetup({ async: false });
  <% end %>
<% end %>

app/views/layouts/_map.html.erb
<script>
//ParkingMap Définition
var handler = Gmaps.build('Google');
handler.buildMap({ internal: {id: 'map'}}, function(){
  var markers = handler.addMarkers(<%=raw @hash.to_json %>);
  handler.bounds.extendWith(markers);
  handler.fitMapToBounds();
});
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta charset="utf-8" />
  <meta name="ROBOTS" content="NOODP" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.5/css/bootstrap.min.css" integrity="sha384-AysaV+vQoT3kOAXZkl02PThvDr8HYKPZhNT5h/CXfBThSRXQ6jW5DO2ekP5ViFdi" crossorigin="anonymous">
  <link href="https://fonts.googleapis.com/css?family=EB+Garamond" rel="stylesheet">
  <%#
    Configure default and controller-, and view-specific titles in
    config/locales/en.yml. For more see:
    https://github.com/calebthompson/title#usage
  %>
  <title><%= title %></title>
  <%= stylesheet_link_tag :application, media: "all" %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= body_class %>">
  <div class="navbar-collapse collapse inverse" id="navbar-header" style="-webkit-padding-before: 1.5em;">
    <div class="container-fluid">
      <div class="about">
        <h4>About</h4>
        <p class="text-muted">
          Yespark est le leader en France de la locaction de parking au mois. Notre backend est construit sur le framework web Ruby on Rails. Nous utilisons la plate-forme de service Heroku pour mettre en ligne notre API et notre application web. Notre réseau de parkings en location compte environ 300 parkings dans toute la France. Notre force ? Un service client de qualité, des applications smartphones iOS et Android à la pointe des technologies mobiles natives, une équipe jeune et dynamique. Cela nous permet de proposer des parkings en location environ 30% moins chers que les locations traditionnelles.
        </p>
      </div>
    </div>
  </div>
  <div class="navbar navbar-static-top navbar-dark bg-inverse" style="-webkit-padding-before: 1.3em;">
    <div class="container-fluid">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-header" aria-controls="navbar-header" aria-expanded="false" aria-label="Toggle navigation"></button>
      <a href="<%= root_path %>" class="navbar-brand">YesPark</a>
      <% unless @is_page_controller %>
        <div class="float-xs-right" style="margin-top: 0.5em">
          <a href="<%= parkings_path %>" class="btn btn-primary btn-sm">Liste des Parkings</a>
          <a href=<%= page_path('maps') %> class="btn btn-secondary btn-sm">La carte des Parkings</a>
        </div>
      <% end %>
    </div>
  </div>

  <% if @is_page_controller %>
    <section class="jumbotron text-xs-center">
      <div class="container">
        <h1 class="jumbotron-heading">YesPark example</h1>
        <p class="lead text-muted">
          Ceci est un exemple d'application web créée sur Heroku pour illustrer la création, la modification et la suppression de Parking.</p>
        <p>
        <a href="<%= parkings_path %>" class="btn btn-primary">Liste des Parkings</a>
        <a href=<%= page_path('maps') %> class="btn btn-secondary">La carte des Parkings</a>
        </p>
      </div>
    </section>
  <% end %>

  <div class="album text-muted">
    <div class="container">
      <%= render "flashes" -%>
      <%= yield %>
    </div>
  </div>

  <footer class="text-muted">
    <div class="container">
      <p class="float-xs-right">
        <a href="#">Back to top</a>
      </p>
    </div>
  </footer>

  <script src="//maps.google.com/maps/api/js?key=<%= ENV.fetch('GOOGLE_MAPS_JS_API') %>"</script>
  <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.0.0/jquery.min.js" integrity="sha384-THPy051/pYDQGanwU6poAc/hOdQxjnOEXzbT+OuUAFqNqFjL+4IGLBgCJC3ZOShY" crossorigin="anonymous"></script>
    <script>window.jQuery</script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.2.0/js/tether.min.js" integrity="sha384-Plbmg8JY28KFelvJVai01l8WyZzrYWG825m+cZ0eDDS1f7d/js6ikvy1+X+guPIB" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/holder/2.9.4/holder.min.js"></script>
    <script>
      $(function () {
        Holder.addTheme("thumb", { background: "#55595c", foreground: "#eceeef", text: "Thumbnail" });
      });
    </script>
  <%= render "javascript" %>
  <%= render "css_overrides" %>

    <%= render "layouts/map" %>
</body>
</html>

app/views/pages/home.html.slim
h1 Parkings

.album.text-muted
  .container
    - Parking.all.each do |parking|
      hr
      = render 'parkings/show', parking: parking

app/views/pages/maps.html.slim
.container
  p
    #map style=("width: 800px; height: 400px;") 
  p
    pre
      = Cowsay.say("Welcome to YesPark's Map", "Cow")

app/views/parkings/_form.html.slim
= form_for @parking do |f|
  - if @parking.errors.any?
    #error_explanation
      h2 = "#{pluralize(@parking.errors.count, "error")} prohibited this parking from being saved:"
      ul
        - @parking.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :address
    = f.text_field :address
  .field
    = f.label :available
    = f.check_box :available
  .field
    = f.label :has_camera
    = f.check_box :has_camera
  .field
    = f.label :has_watchman
    = f.check_box :has_watchman
  .field
    = f.label :zip_code
    = f.text_field :zip_code
  .field
    = f.label :city
    = f.text_field :city
  .field
    = f.label :main_picture
    = f.text_field :main_picture
  .field
    = f.label :price_month
    = f.text_field :price_month
  .actions = f.submit

app/views/parkings/_show.html.slim
.row
  .col-xs-6
    = link_to image_tag(parking.main_picture, border: 0, alt: "Card image cap", class: "img-responsive"), parking
    p.card-text 
      strong= parking.slug
  .col-xs-6
    p
      p
        strong Name:
        '
        = parking.name
      p
        strong Address:
        '
        = parking.address
      p
        strong Available:
        '
        = parking.available
      p
        strong Has camera:
        '
        = parking.has_camera
      p
        strong Has watchman:
        '
        = parking.has_watchman
      p
        strong Zip code:
        '
        = parking.zip_code
      p
        strong City:
        '
        = parking.city
      p
        strong Price month:
        '
        = humanized_money_with_symbol parking.price_month
      p
        = link_to 'Show', parking
        '
        = link_to 'Edit', edit_parking_path(parking)
        '
        = link_to 'Destroy', parking, data: { confirm: 'Are you sure?' }, method: :delete

app/views/parkings/edit.html.slim
h1 Editing parking

== render 'form'

= link_to 'Show', @parking
'|
= link_to 'Back', parkings_path

app/views/parkings/index.html.slim
h1 Listing parkings

table.table.table-hover.table-sm
  thead
    tr
      th Name
      th Address
      th Available
      th camera?
      th watchman?
      th Zip code
      th City
      th picture
      th Price/month
      td Actions
      td

  tbody
    - @parkings.each do |parking|
      tr scope='row'
        td = parking.name
        td = parking.address
        td = parking.available
        td = parking.has_camera
        td = parking.has_watchman
        td = parking.zip_code
        td = parking.city
        td = humanized_money_with_symbol parking.price_month
        td
          = link_to image_tag(parking.main_picture, border: 0, alt: parking.name, width: '100px', height: 'auto', class: "img-responsive"), parking
        td colspan="2"
          = link_to 'Show', parking
          '
          = link_to 'Edit', edit_parking_path(parking)
          '
          = link_to 'Destroy', parking, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Parking', new_parking_path

app/views/parkings/new.html.slim
h1 New parking

== render 'form'

= link_to 'Back', parkings_path

app/views/parkings/show.html.slim
br
br
= render 'parkings/show', parking: @parking
hr
= link_to 'Parkings List', parkings_path